language: python

python:
  - "2.7"

env:
  - TRAVIS_NODE_VERSION="4.5"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
    - node_modules

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - make build

script:
  - make tests

notifications:
  slack:
    secure: j510O1sCqnVN12VQ7GVW+uADxZaPp2cGvPDDVdqyVMIDPR6LlkFegAu/4cNJ907Eyo2ytMD/jYfNE4NmnqULDvyjzNDIYAltKxoDdUDGazIUK1hanMXuf5tDIzFyJX3NYB8V168EJnyjxUsbQ1N46DsG+AqJZLdW+tF63EMI8czmtuFa524cx6T+vt48vnrfJIcRupPllDmwQyiA3y2ufsRiYQ0ju+Yjn8p1e6LKikZk8lcdzpnwSKkcMYep1WUx9fRkUd5v7OwpggmCA4XeopkFLhuOmS7y6nzcy3R8gUB0P8Js7MQi2TKa0lkDkmSLshGHxXS2PqWD6EvgF638Kx2Wx1VYgtzruXJDWKznYHdmrbQGDu4B45bqvWTbz3+3JEEDQd4CQOQ3jTm6zeauMGn9S6vSM0pSJQk6OgQBGWFbsoCcwwboCiSbdcyGj4gao3zvYoDdoY5t3CXj+5xygbMCTYr3rbrQMig/BWonZSWtc58eGeXV82WK9sYAlnryomvrJ9F9NSzAnfp4CaPrWyyMyMlKpC7XOrENlndi/WvI9I8VvdcWtWnpsqLrwY5lN4hRurAn1H/qs+8tBZ6YfohxBgdZ4POJCZNZlsskQ4nnMFPTOlLKvta+VIDZd+XcuKs2ZaH8vL5nF6HW1rJp8qvsJ7HGtMW6wURP1Cu2u5M=
